# Add packages when needed

name: nebari-demo
channels:
- conda-forge
dependencies:
- python=3.9
- ipykernel
- ipywidgets
- numpy
- pandas
- matplotlib
- s3fs
- pyarrow
- jupyterlab
- jupyterlab-spellchecker
- nebari-dask
- panel
- hvplot
- pip
- pip:
  - nebari
  - nasdaq-data-link
