channels:
  - conda-forge
dependencies:
  - python=3.12
  - ipykernel
  - ipywidgets
  - numpy
  - pandas
  - matplotlib
  - s3fs
  - pyarrow
  - jupyterlab
  - nebari-dask
  - panel
  - hvplot
  - streamlit
  - scikit-learn
  - bokeh
  - gcsfs
  - tensorflow
  - polars
  - bokeh_sampledata
  - papermill
  - pystac-client
  - planetary-computer
  - pytorch
  - torchvision
  - pip
  - pip:
      - nasdaq-data-link
variables: {}
